server:
  port: 8085
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

spring:
  application:
    name: notification-service
    # Apache Kafka
  kafka:
    bootstrap:
      servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.type.mapping: event:com.microservicesproject.notificationservice.event.OrderPlacedEvent

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# Zipkin - distributed tracing
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans/
  tracing:
    sampling:
      probability: 1
  # Actuator Prometheus Endpoint
  endpoints:
    web:
      exposure:
        include: prometheus
