version: "3.8"
services:
  postgres_orderservice:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_orderservice_data:/var/lib/postgresql/data/

  postgres_inventoryservice:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_inventoryservice_data:/var/lib/postgresql/data/

volumes:
  postgres_orderservice_data:
  postgres_inventoryservice_data:
