version: "3.8"
services:
  order-service-postgres:
    image: postgres
    container_name: order-service-postgres
    labels:
      com.microservice-project-tutorial.order-service: order-service
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_USER: ${POSTGRES_USER}
    # user: postgres
    # command: >
    #   sh -c "postgres postgres -D /var/lib/postgresql/data &&
    #           psql -U postgres postgres -f /docker-entrypoint-initdb.d/init-user-db.sh"
    volumes:
      - order-service-postgres:/var/lib/postgresql/data/
      - ./order-service/src/main/resources/db:/docker-entrypoint-initdb.d

  inventory-service-postgres:
    image: postgres
    container_name: inventory-service-postgres
    labels:
      com.microservice-project-tutorial.inventory-service: inventory-service
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_USER: ${POSTGRES_USER}
    # user: postgres
    # command: >
    #   sh -c "postgres postgres -D /var/lib/postgresql/data &&
    #           psql -U postgres postgres -f /docker-entrypoint-initdb.d/init-user-db.sh"
    volumes:
      - inventory-service-postgres:/var/lib/postgresql/data/
      - ./inventory-service/src/main/resources/db:/docker-entrypoint-initdb.d

volumes:
  order-service-postgres:
  inventory-service-postgres:
