version: "3.8"
services:
  # Postgres db server
  order-service-postgres:
    image: postgres
    container_name: order-service-postgres
    labels:
      com.microservice-project-tutorial.order-service: order-service
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - order-service-postgres:/var/lib/postgresql/data/
      - ./order-service/src/main/resources/db:/docker-entrypoint-initdb.d
  inventory-service-postgres:
    image: postgres
    container_name: inventory-service-postgres
    labels:
      com.microservice-project-tutorial.inventory-service: inventory-service
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - inventory-service-postgres:/var/lib/postgresql/data/
      - ./inventory-service/src/main/resources/db:/docker-entrypoint-initdb.d

  # Mongo db server
  product-service-mongodb:
    image: mongo
    container_name: product-service-mongodb
    labels:
      com.microservice-project-tutorial.product-service: product-service
    ports:
      - "27017:27017"
    expose:
      - "27017"
    # environment:
    # MONGO_INITDB_DATABASE: product-service
    # MONGODB_USERNAME: ${MONGODB_USERNAME}
    # MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    # MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
    # MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - ./product-service/src/main/resources/db:/docker-entrypoint-initdb.d

  # Apache Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

volumes:
  order-service-postgres:
  inventory-service-postgres:
  mongo-data:
