##Server
server:
  port: 7080

##Spring basic application configuration
spring:
  application:
    name: api-gateway
  ## Gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-statics
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservice-realm
          jwk-set-uri: http://localhost:8181/realms/spring-boot-microservice-realm/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/realms/spring-boot-microservice-realm
        registration:
          spring-cloud-client:
            provider: keycloak
            client-id: spring-cloud-client
            client-secret: pztyv7oqhiHdAc0wiXWQquU5VwKAIoqK
            authorization-grant-type: authorization_code
            scope: openid

## Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

## Loggin
logging:
  level:
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

## Zipkin distributed tracing
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      # http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
