global:
  scrape_interval: 10s # The amount of time prometheus will scrap from srping boot application
  evaluation_interval: 10s

scrape_configs:
  - job_name: "product_service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["product-service:9001"]
        labels:
          application: "Product Service Application"
  - job_name: "order_service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["order-service:8081"]
        labels:
          application: "Order Service Application"
  - job_name: "inventory_service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["inventory-service:8082"]
        labels:
          application: "Inventory Service Application"
  - job_name: "notification-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["notification-service:8085"]
        labels:
          application: "Notification Service Application"
