server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5433/orderservice
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  kafka:
    bootstrap-servers: broker:29092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/spring-boot-microservice-realm
          jwk-set-uri: http://keycloak:8080/realms/spring-boot-microservice-realm/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
