server:
  port: 8761

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

## Zipkin distributed tracing
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      # http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  # Actuator Prometheus Endpoint
  endpoints:
    web:
      exposure:
        include: prometheus
