server:
  port: 9001

spring:
  data:
    mongodb:
      host: product-service-mongodb
      port: 27017
      database: product-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/spring-boot-microservice-realm
          jwk-set-uri: http://keycloak:8080/realms/spring-boot-microservice-realm/protocol/openid-connect/certs

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
