spring:
  application:
    name: product-service
  profiles:
    active: default
  data:
    mongodb:
        host: localhost
        port: 27017
        database: product-service
        uri: mongodb://localhost:27017/product
server:
  port: 9001