server:
  port: 9001
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

spring:
  application:
    name: product-service
  # profiles:
  #   active: default
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-service
      # username: root
      # password: example
      # uri: mongodb://localhost:27017/product
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/spring-boot-microservice-realm/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

## Zipkin distributed tracing
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      # http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  # Actuator Prometheus Endpoint
  endpoints:
    web:
      exposure:
        include: prometheus
