server:
  port: 9001

spring:
  application:
    name: product-service
  profiles:
    active: default
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-service
      # username: root
      # password: example
      # uri: mongodb://localhost:27017/product

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
