server:
  port: 8082
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5434/inventoryservice
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-boot-microservice-realm
          jwk-set-uri: http://localhost:8080/realms/spring-boot-microservice-realm/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

## Zipkin distributed tracing
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      # http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
